<?php
require '../vendor/autoload.php'; // Include Composer autoloader
include('authentication.php');

use Dompdf\Dompdf;

// Fetch donation data
$query = "
    SELECT d.donor_name, d.amount, d.payment_type, d.donation_date, 
           CONCAT(d.province, ', ', d.district) AS location
    FROM donations d";
$result = mysqli_query($con, $query);

// Prepare data for the table
$donations = [];
while ($row = mysqli_fetch_assoc($result)) {
    $donations[] = $row;
}

// Generate HTML for the report
ob_start();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation Report</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f9f9f9;
        }

        header {
            text-align: center;
            background-color: #4CAF50;
            color: white;
            padding: 15px 0;
            font-size: 20px;
        }

        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            text-align: center;
            background-color: #4CAF50;
            color: white;
            padding: 10px 0;
            font-size: 12px;
        }

        main {
            padding: 30px;
        }

        h1,
        h3 {
            color: #333;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background-color: white;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #4CAF50;
            color: white;
            font-size: 16px;
            padding: 8px;
            text-align: center;
        }

        td {
            padding: 10px;
            font-size: 14px;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:hover {
            background-color: #ddd;
        }

        .no-data {
            text-align: center;
            font-style: italic;
            color: #999;
        }
    </style>
</head>

<body>
    <header>
        Donation Report - <?= date('Y-m-d') ?>
    </header>

    <main>
        <h1>Donation Report</h1>
        <h3>Donation History</h3>

        <table>
            <thead>
                <tr>
                    <th>Donor Name</th>
                    <th>Location</th>
                    <th>Amount (LKR)</th>
                    <th>Payment Method</th>
                    <th>Donation Date</th>
                </tr>
            </thead>
            <tbody>
                <?php if (count($donations) > 0): ?>
                    <?php foreach ($donations as $donation): ?>
                        <tr>
                            <td><?= htmlspecialchars($donation['donor_name']) ?></td>
                            <td><?= htmlspecialchars($donation['location']) ?></td>
                            <td><?= number_format($donation['amount'], 2) ?></td>
                            <td><?= htmlspecialchars($donation['payment_type']) ?></td>
                            <td><?= htmlspecialchars($donation['donation_date']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php else: ?>
                    <tr>
                        <td colspan="5" class="no-data">No donation records available.</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </main>

    <footer>
        Generated by GiveHope - <?= date('Y') ?>
    </footer>
</body>

</html>
<?php
$html = ob_get_clean();

// Initialize Dompdf and load the HTML
$dompdf = new Dompdf();
$dompdf->loadHtml($html);

// (Optional) Set paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the PDF
$dompdf->render();

// Output the generated PDF to the browser
$dompdf->stream('Donation_Report.pdf', ['Attachment' => true]);
?>