<?php
require '../vendor/autoload.php'; // Include Composer autoloader for Dompdf
include('authentication.php');

use Dompdf\Dompdf;

// Get filters from GET parameters
$campaignCategory = isset($_GET['campaign_category']) && !empty($_GET['campaign_category']) ? $_GET['campaign_category'] : null;
$filterStartDate = isset($_GET['start_date']) && !empty($_GET['start_date']) ? $_GET['start_date'] : null;
$filterEndDate = isset($_GET['end_date']) && !empty($_GET['end_date']) ? $_GET['end_date'] : null;

// Build the query with optional filters
$query = "SELECT * FROM campaigns WHERE 1=1";

if (!empty($campaignCategory)) {
    $query .= " AND category = '" . mysqli_real_escape_string($con, $campaignCategory) . "'";
}

if (!empty($filterStartDate)) {
    $query .= " AND start_date >= '" . mysqli_real_escape_string($con, $filterStartDate) . "'";
}

if (!empty($filterEndDate)) {
    $query .= " AND end_date <= '" . mysqli_real_escape_string($con, $filterEndDate) . "'";
}

// Execute the query
$result = mysqli_query($con, $query);

if (!$result) {
    die("Query Error: " . mysqli_error($con) . " - Query: " . $query);
}

// Fetch campaigns
$campaigns = [];
while ($row = mysqli_fetch_assoc($result)) {
    $campaigns[] = $row;
}

// Generate HTML for the report
ob_start();
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Campaign Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            text-align: center;
            background-color: #4CAF50;
            color: white;
            padding: 10px 0;
        }

        footer {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            text-align: center;
            background-color: #4CAF50;
            color: white;
            padding: 5px 0;
            font-size: 12px;
        }

        h1,
        h3 {
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px auto;
        }

        table,
        th,
        td {
            border: 1px solid #ddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>

<body>
    <header>
        Campaign Report - <?= date('Y-m-d') ?>
    </header>

    <h1>Campaign Report</h1>
    <h3>
        <?= $campaignCategory ? "Category: " . htmlspecialchars($campaignCategory) : "All Categories" ?>
        <?= $filterStartDate ? " | From: " . htmlspecialchars($filterStartDate) : "" ?>
        <?= $filterEndDate ? " | To: " . htmlspecialchars($filterEndDate) : "" ?>
    </h3>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Location</th>
                <th>Category</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Goal (LKR)</th>
            </tr>
        </thead>
        <tbody>
            <?php if (count($campaigns) > 0): ?>
                <?php foreach ($campaigns as $campaign): ?>
                    <tr>
                        <td><?= htmlspecialchars($campaign['id']); ?></td>
                        <td><?= htmlspecialchars($campaign['title']); ?></td>
                        <td><?= htmlspecialchars($campaign['location']); ?></td>
                        <td><?= htmlspecialchars($campaign['category']); ?></td>
                        <td><?= htmlspecialchars($campaign['start_date']); ?></td>
                        <td><?= htmlspecialchars($campaign['end_date']); ?></td>
                        <td>LKR <?= number_format($campaign['goal'], 2); ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7" class="text-center">No Campaigns Found</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <footer>
        Generated by GiveHope - <?= date('Y') ?>
    </footer>
</body>

</html>
<?php
$html = ob_get_clean();

// Initialize Dompdf and load the HTML
$dompdf = new Dompdf();
$dompdf->loadHtml($html);

// (Optional) Set paper size and orientation
$dompdf->setPaper('A4', 'portrait');

// Render the PDF
$dompdf->render();

// Output the generated PDF to the browser
$dompdf->stream('Campaign_Report.pdf', ['Attachment' => true]);
?>